[package]
name = "clowder"
version = "0.1.0"
authors = ["Jonathan Anderson <jonathan.anderson@mun.ca>"]

[dependencies]
chrono = "0.2"
chrono-humanize = "0.0.6"
diesel = { version = "0.9.0", features = ["chrono"] }
diesel_codegen = { version = "0.9.0", features = ["postgres"] }
dotenv = "0.8.0"
maud = { version = "*", features = ["rocket"] }
maud_macros = "*"
rocket = "0.1.6"
rocket_codegen = "0.1.6"
#serde = "0.8"
#serde_derive = "0.8"
#tera = "*"

#[dependencies.rocket_contrib]
#version = "*"
#default-features = false
#features = ["tera_templates"]
