[database]
	filename = "clowder.db"

[server]
	ip		= "192.168.1.1"
	subnetmask	= "255.255.255.0"
	duration	= "24h"
	dns		= "192.168.1.1"
	router		= "192.168.1.1"
	domainname	= "musec.engr.mun.ca"

[machines]
	ipstart = "192.168.1.20"
	iprange = 10

[devices]
	ipstart = "192.168.1.100"
	iprange = 10
