/* Generated by `diesel print-schema` */

table! {
    disks (id) {
        id -> Int4,
        machine_id -> Int4,
        vendor -> Nullable<Text>,
        model -> Nullable<Text>,
        capacity_gb -> Int4,
        ssd -> Bool,
    }
}

table! {
    emails (id) {
        id -> Int4,
        user_id -> Int4,
        email -> Text,
    }
}

table! {
    machines (id) {
        id -> Int4,
        name -> Varchar,
        arch -> Varchar,
        microarch -> Varchar,
        cores -> Int4,
        memory_gb -> Int4,
    }
}

table! {
    nics (id) {
        id -> Int4,
        machine_id -> Int4,
        vendor -> Nullable<Text>,
        model -> Nullable<Text>,
        mac_address -> Bpchar,
        speed_gbps -> Int4,
    }
}

table! {
    reservations (id) {
        id -> Int4,
        user_id -> Int4,
        machine_id -> Int4,
        scheduled_start -> Timestamptz,
        scheduled_end -> Nullable<Timestamptz>,
        actual_end -> Nullable<Timestamptz>,
        pxe_path -> Nullable<Text>,
        nfs_root -> Nullable<Text>,
    }
}

table! {
    role_assignments (id) {
        id -> Int4,
        user_id -> Int4,
        role_id -> Int4,
    }
}

table! {
    roles (id) {
        id -> Int4,
        name -> Text,
        can_alter_users -> Bool,
        can_view_users -> Bool,
    }
}

table! {
    users (id) {
        id -> Int4,
        username -> Varchar,
        name -> Text,
    }
}

joinable!(disks -> machines (machine_id));
joinable!(nics -> machines (machine_id));
joinable!(emails -> users (user_id));
joinable!(role_assignments -> users (user_id));
joinable!(role_assignments -> roles (role_id));
joinable!(reservations -> users (user_id));
joinable!(reservations -> machines (machine_id));
